# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 006e2f866b154df70e4ed2b67d7990c076f10ce3e6ca8bbe261ca568b8c060ba17ca7ff9588c8330f08ca00b136eaac00acefb89a17b926e2fadfdb5c5a06293

test:
  secret_key_base: f9d573d5caf34359e77690b569a106928ec88774ccbe457d66ab3b398c2b71e010fc9dfa2db3caa2aa9fca15e5bc1c08ad1d50fa94bfc968558cdd8fc63491fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
